#!/bin/bash
# Ralph Wiggum Interactive Setup
# Run this to configure Ralph for your project

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Ralph Wiggum Setup Wizard                          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# -----------------------------------------------------------------------------
# Check for existing configuration
# -----------------------------------------------------------------------------
if [ -f "ralph.conf" ]; then
    echo -e "${YELLOW}Found existing ralph.conf${NC}"
    read -p "Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

# -----------------------------------------------------------------------------
# Select AI Harness
# -----------------------------------------------------------------------------
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  Step 1: Select AI Harness${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Which AI CLI will you use?"
echo ""
echo "  1) Claude Code (claude) - Anthropic's CLI [recommended]"
echo "  2) OpenCode (opencode) - Multi-model agentic coding"
echo "  3) Codex CLI (codex) - OpenAI's coding agent"
echo "  4) Custom command"
echo ""
read -p "Select [1-4]: " harness_choice

case $harness_choice in
    1)
        HARNESS="claude"
        MODEL=""
        ;;
    2)
        HARNESS="opencode"
        echo ""
        echo "Available models for OpenCode:"
        echo "  - gpt-4, gpt-4-turbo, gpt-4o"
        echo "  - claude-3-opus, claude-3-sonnet, claude-3-haiku"
        echo "  - gemini-pro, gemini-ultra"
        read -p "Model name: " MODEL
        ;;
    3)
        HARNESS="codex"
        echo ""
        echo "Available models for Codex:"
        echo "  - o1 (reasoning, slower)"
        echo "  - o1-mini (faster reasoning)"
        echo "  - gpt-4, gpt-4-turbo"
        read -p "Model name: " MODEL
        ;;
    4)
        HARNESS="custom"
        echo ""
        echo "Enter your custom command."
        echo "Use {PROMPT_FILE} as placeholder for the prompt file."
        echo ""
        echo "Example: my-agent run --file {PROMPT_FILE} --auto-approve"
        echo ""
        read -p "Custom command: " CUSTOM_CMD
        MODEL=""
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

# -----------------------------------------------------------------------------
# Configure subtasks
# -----------------------------------------------------------------------------
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  Step 2: Subagent Configuration${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Allow spawning parallel subagents in build mode?"
echo "(Enables Task tool for parallel implementation)"
echo ""
read -p "Allow subtasks? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ALLOW_SUBTASKS=true
else
    ALLOW_SUBTASKS=false
fi

# -----------------------------------------------------------------------------
# Configure loop settings
# -----------------------------------------------------------------------------
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  Step 3: Loop Settings${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
read -p "Max iterations [100]: " MAX_ITERATIONS
MAX_ITERATIONS=${MAX_ITERATIONS:-100}

read -p "Sleep between iterations (seconds) [5]: " SLEEP_BETWEEN
SLEEP_BETWEEN=${SLEEP_BETWEEN:-5}

# -----------------------------------------------------------------------------
# Write configuration
# -----------------------------------------------------------------------------
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  Writing Configuration${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

cat > ralph.conf << CONF
# Ralph Wiggum Configuration
# Generated by setup.sh on $(date)

# AI Harness: claude | opencode | codex | custom
HARNESS="$HARNESS"

# Model (for opencode/codex)
MODEL="$MODEL"

# Custom command (for custom harness)
CUSTOM_CMD="$CUSTOM_CMD"

# Loop settings
MAX_ITERATIONS=$MAX_ITERATIONS
SLEEP_BETWEEN=$SLEEP_BETWEEN

# Default mode
MODE="build"

# Allow Task tool for subagents in build mode
ALLOW_SUBTASKS=$ALLOW_SUBTASKS
CONF

echo -e "${GREEN}Created ralph.conf${NC}"

# -----------------------------------------------------------------------------
# Create directory structure if needed
# -----------------------------------------------------------------------------
echo ""
if [ ! -d "specs" ]; then
    mkdir -p specs
    echo -e "${GREEN}Created specs/ directory${NC}"
fi

if [ ! -f "AGENTS.md" ]; then
    echo -e "${YELLOW}Note: Copy AGENTS.md template and customize for your project${NC}"
fi

if [ ! -f "PROMPT_plan.md" ]; then
    echo -e "${YELLOW}Note: Copy PROMPT_plan.md template${NC}"
fi

if [ ! -f "PROMPT_build.md" ]; then
    echo -e "${YELLOW}Note: Copy PROMPT_build.md template${NC}"
fi

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Configuration:"
echo "  Harness:        $HARNESS"
[[ -n "$MODEL" ]] && echo "  Model:          $MODEL"
echo "  Allow subtasks: $ALLOW_SUBTASKS"
echo "  Max iterations: $MAX_ITERATIONS"
echo "  Sleep between:  ${SLEEP_BETWEEN}s"
echo ""
echo "Next steps:"
echo "  1. Customize AGENTS.md with your build/test/lint commands"
echo "  2. Write specs in specs/*.md using JTBD format"
echo "  3. Run: ./loop.sh --plan    # Generate implementation plan"
echo "  4. Run: ./loop.sh --build   # Implement from plan"
echo ""
